import 'dart:convert';

import 'package:quiz1/core/utils/test1.dart';
import 'package:quiz1/core/utils/test2.dart';

class Autogenerated {
  Company? company;

  Autogenerated({this.company});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    company =
        json['company'] != null ? Company.fromJson(json['company']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (company != null) {
      data['company'] = company!.toJson();
    }
    return data;
  }

  @override
  String toString() {
    return 'Autogenerated(company: $company)';
  }
}

class Company {
  int? isActive;
  String? name;
  Address? address;
  String? established;
  List<Departments>? departments;

  Company(
      {this.isActive,
      this.name,
      this.address,
      this.established,
      this.departments});

  Company.fromJson(Map<String, dynamic> json) {
    isActive = json['isActive'];
    name = json['name'];
    address =
        json['address'] != null ? Address.fromJson(json['address']) : null;
    established = json['established'];
    if (json['departments'] != null) {
      departments = <Departments>[];
      json['departments'].forEach((v) {
        departments!.add(Departments.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['isActive'] = isActive;
    data['name'] = name;
    if (address != null) {
      data['address'] = address!.toJson();
    }
    data['established'] = established;
    if (departments != null) {
      data['departments'] = departments!.map((v) => v.toJson()).toList();
    }
    return data;
  }

  @override
  String toString() {
    return 'Company(isActive: $isActive, name: $name, address: $address, established: $established, departments: $departments)';
  }
}

class Address {
  String? street;
  String? city;
  String? state;
  String? postalCode;

  Address({this.street, this.city, this.state, this.postalCode});

  Address.fromJson(Map<String, dynamic> json) {
    street = json['street'];
    city = json['city'];
    state = json['state'];
    postalCode = json['postalCode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['street'] = street;
    data['city'] = city;
    data['state'] = state;
    data['postalCode'] = postalCode;
    return data;
  }

  @override
  String toString() {
    return 'Address(street: $street, city: $city, state: $state, postalCode: $postalCode)';
  }
}

class Departments {
  String? deptId;
  String? name;
  String? manager;
  double? budget;
  int? year;
  Availability? availability;
  String? meetingTime;

  Departments(
      {this.deptId,
      this.name,
      this.manager,
      this.budget,
      this.year,
      this.availability,
      this.meetingTime});

  Departments.fromJson(Map<String, dynamic> json) {
    deptId = json['deptId'];
    name = json['name'];
    manager = json['manager'];
    budget = json['budget'];
    year = json['year'];
    availability = json['availability'] != null
        ? Availability.fromJson(json['availability'])
        : null;
    meetingTime = json['meeting_time'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['deptId'] = deptId;
    data['name'] = name;
    data['manager'] = manager;
    data['budget'] = budget;
    data['year'] = year;
    if (availability != null) {
      data['availability'] = availability!.toJson();
    }
    data['meeting_time'] = meetingTime;
    return data;
  }

  @override
  String toString() {
    return 'Departments(deptId: $deptId, name: $name, manager: $manager, budget: $budget, year: $year, availability: $availability, meetingTime: $meetingTime)';
  }
}

class Availability {
  bool? online;
  bool? inStore;

  Availability({this.online, this.inStore});

  Availability.fromJson(Map<String, dynamic> json) {
    online = json['online'];
    inStore = json['inStore'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['online'] = online;
    data['inStore'] = inStore;
    return data;
  }

  @override
  String toString() {
    return 'Availability(online: $online, inStore: $inStore)';
  }
}

void main() {
  print("With Ai Model:");
  Map<String, dynamic> parsedJson2 = jsonDecode(test2);
  Autogenerated autogenerated2 = Autogenerated.fromJson(parsedJson2);
  print(autogenerated2);
}
